### ISSUE TITLE
How mesh is extracted?

### ISSUE THREAD

**Issue by anhquancao** [jetd1/NeRFusion#1]
Hi @jetd1,

Thanks for your great work!
I would like to ask how the mesh was extracted? 
I checked the paper but could find it, maybe I missed something.

Thank you.

**Comment by liusang** [comment]
@anhquancao  I see that there is a depth map in the model output in the code. Maybe you can get mesh by combining the depth map with the mvs code

**Comment by anhquancao** [comment]
Hi @liusang , thanks for your info!
