### ISSUE TITLE
cam_bbox.txt of ScanNet dataset

### ISSUE THREAD

**Issue by jzhzhang** [jetd1/NeRFusion#6]
Hi, thanks for sharing the code.

I plan to test this method with other sequences of scannet. But I noticed that there is a ```cam_bbox.txt``` in the prepared data. However, I can not find any related information in the original scannet dataset. So could you kindly provide more information about the ```cam_bbox.txt```?

**Comment by jetd1** [comment]
Hi the `cam_bbox.txt` is simply the `min_xyz` and `max_xyz` of your input cameras. We have provided a simple utility script at `scripts/scannet_get_bbox.py` for generating this information on any ScanNet scene.
